server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8080}

llm:
  mode: ${PGPT_MODE:mock}

embedding:
  mode: ${PGPT_EMBED_MODE:mock}

ollama:
  llm_model: ${PGPT_OLLAMA_LLM_MODEL:gemma2}
  embedding_model: ${PGPT_OLLAMA_EMBEDDING_MODEL:nomic-embed-text}
  api_base: ${PGPT_OLLAMA_API_BASE:http://ollama:11434}
  embedding_api_base: ${PGPT_OLLAMA_EMBEDDING_API_BASE:http://ollama:11434}
  tfs_z: ${PGPT_OLLAMA_TFS_Z:1.0}
  top_k: ${PGPT_OLLAMA_TOP_K:40}
  top_p: ${PGPT_OLLAMA_TOP_P:0.9}
  repeat_last_n: ${PGPT_OLLAMA_REPEAT_LAST_N:64}
  repeat_penalty: ${PGPT_OLLAMA_REPEAT_PENALTY:1.2}
  request_timeout: ${PGPT_OLLAMA_REQUEST_TIMEOUT:600.0}
  autopull_models: ${PGPT_OLLAMA_AUTOPULL_MODELS:true}

nodestore:
  database: postgres

vectorstore:
  database: postgres

postgres:
  host: ${POSTGRES_HOST:postgres}
  port: ${POSTGRES_PORT:5432}
  databse: ${POSTGRES_DB:postgres}
  user: ${POSTGRES_USER:postgres}
  password: ${POSTGRES_PASSWORD:hackme}

ui:
  enabled: true
  path: /
