# GPU is not available in Docker on macos
# You should start Ollama seperately on host machine

services:
  pgpt:
    build:
      context: ./
      dockerfile: ./pgpt/Dockerfile
    ports:
      - 8001:8001
    expose:
      - 8001
    volumes:
     - ./pgpt/settings-docker.yaml:/home/worker/app/settings-docker.yaml
    environment:
      PORT: 8001
      PGPT_PROFILES: docker
      PGPT_MODE: ollama
      PGPT_EMBED_MODE: ollama
      PGPT_OLLAMA_API_BASE: http://host.docker.internal:11434
      PGPT_OLLAMA_EMBEDDING_API_BASE: http://host.docker.internal:11434
      PGPT_OLLAMA_LLM_MODEL: my-model
      PGPT_OLLAMA_EMBEDDING_MODEL: my-embed
      PGPT_EMBED_DIM: 1024
      POSTGRES_PASSWORD: goida
    restart: always
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_PASSWORD=goida
    volumes:
      - postgres:/var/lib/postgresql/data
  migrate:
    build:
      dockerfile: docker/migrate.Dockerfile
      context: .
  fetcher:
    build:
      dockerfile: docker/fetcher.Dockerfile
      context: .
    volumes:
      - ./content:/app/content
    env_file:
      - .env
      - .env.secrets
    restart: always
  indexer:
    build:
      dockerfile: docker/indexer.Dockerfile
      context: .
    volumes:
      - ./content:/app/content
    env_file:
      - .env
      - .env.secrets
    restart: always
volumes:
  postgres: