"""Added published field

Revision ID: 3fcf4f1328f2
Revises: c7f9126f77dc
Create Date: 2024-12-01 18:30:59.792723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcf4f1328f2'
down_revision: Union[str, None] = 'c7f9126f77dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('published', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'published')
    # ### end Alembic commands ###
